CLONE7/Assessment7-master/Assessment6/QLHOLIDAYPARTY/QLHOLIDAYPARTY/Controllers/IdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using QLHOLIDAYPARTY.Models;

namespace QLHOLIDAYPARTY.Controllers
{
    public class IdentityController : Controller
    {
        public UserManager<RegisterModel> UserManager => HttpContext.GetOwinContext().Get<UserManager<RegisterModel>>();

        public ActionResult Registration()
        {
            return View(new RegisterModel());
        }

        [HttpPost]
        public ActionResult Registration(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                model.g.url = "EMPTY";
                var userManager = HttpContext.GetOwinContext().Get<UserManager<RegisterModel>>();
                var id = UserManager.Create(new RegisterModel(model.g.EmailAddress), model.Password);
                if (id.Succeeded)
                {
                    PartyDBEntities1 p = new PartyDBEntities1();
                    p.Guests.Add(model.g);
                    p.SaveChanges();
                    TempData["1"] = model.g.EmailAddress;
                    return RedirectToAction("Done", "Home");
                }
                ModelState.AddModelError("", id.Errors.FirstOrDefault());
            }
            return View(model);
        }

        public ActionResult Login()
        {

            return View(new RegisterModel());
        }

        [HttpPost]
        public ActionResult Login(RegisterModel model)
        {
            if (ModelState.IsValid)
            {  
                var authManager = HttpContext.GetOwinContext().Authentication;
                var user = UserManager.Find(model.UserName, model.Password);
                if (user != null)
                {
                    var ident = UserManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
                    authManager.SignIn(new AuthenticationProperties { IsPersistent = false }, ident);
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", "Idiot");
            return View(model);
        }

        public ActionResult Logout()
        {
            var AM = HttpContext.GetOwinContext().Authentication;
            AM.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> deleteUser(string email)
        {
            PartyDBEntities1 shop = new PartyDBEntities1();
            Guest dedPerson = shop.Guests.Find(email);
            var userEmail = dedPerson.EmailAddress;
            if (userEmail == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByNameAsync(dedPerson.EmailAddress);
            if (User.Identity.Name == userEmail)
            {
                var AM = HttpContext.GetOwinContext().Authentication;
                AM.SignOut();
            }
            await UserManager.DeleteAsync(user);

            //////////////////////////////////////////////////////

            shop.Guests.Remove(dedPerson);
            shop.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

CLONE7/Assessment7-master/Assessment6/QLHOLIDAYPARTY/QLHOLIDAYPARTY/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/JAVA.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink((User.Identity.IsAuthenticated) ? User.Identity.Name : "Welcome", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Register", "Registration", "Identity")</li>
                        <li>@Html.ActionLink("Login", "Login", "Identity")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("bring Dish", "Dish", "Home")</li>
                        <li>@Html.ActionLink("Current Dishes", "dishDisplay", "Home")</li>
                        <li>@Html.ActionLink("Guest List", "displayGuest", "Home")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Identity")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   
</body>
</html>